services:
  # Nomad Admission Control Proxy
  # https://github.com/mxab/nacp/
  nacp:
    image: ghcr.io/mxab/nacp:v0.8.0
    # FixMe: Default user "10001" does not have access to TLS certs
    user: root
    container_name: nomad${NOMAD_NODE_NUM}-nacp
    command: -config /etc/nacp/config.hcl
    network_mode: host
    restart: always
    configs:
    - source: nacp-config.hcl
      target: /etc/nacp/config.hcl
    volumes:
    - ./tls:/opt/tls:ro

  nomad:
    image: ghcr.io/olljanat/nomad-simplified:${VERSION}
    container_name: nomad${NOMAD_NODE_NUM}
    hostname: nomad${NOMAD_NODE_NUM}
    entrypoint: /bin/server-entry.sh
    command: nomad agent -server -config=/etc/nomad.d -config=/etc/nomad.d/role/server.hcl -region=${REGION} -dc=${DATACENTER}
    environment:
      NODE_IP: ${NODE_IP}
      SERVER1: ${SERVER1}
      SERVER2: ${SERVER2}
      SERVER3: ${SERVER3}
    pid: host
    ipc: host
    # FixMe: It might be possible to run Nomad servers without root permission
    # https://github.com/hashicorp/nomad/issues/13669
    privileged: true
    network_mode: host
    restart: always
    healthcheck:
      test:
      - CMD
      - /bin/sh
      - -c
      - wget -O - -q "http://127.0.0.1:4646/v1/agent/health" | grep -q '{"server":{"message":"ok","ok":true}}'
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 30s

    # Trigger graceful shutdown with SIGINT which Nomad agent is listening
    # and give it 5 minutes handle active connections before killing container
    stop_grace_period: 5m
    stop_signal: SIGINT

    volumes:
    - nomad:/opt/nomad
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./tls:/opt/tls:ro

  coredns:
    image: ghcr.io/olljanat/nomad-simplified:${VERSION}
    container_name: nomad${NOMAD_NODE_NUM}-coredns
    command: coredns -conf /etc/coredns/Corefile
    environment:
      NOMAD_TOKEN: ${COREDNS_NOMAD_TOKEN}
      NOMAD_SKIP_VERIFY: "true"
      SERVER1: ${SERVER1}
      SERVER2: ${SERVER2}
      SERVER3: ${SERVER3}
      DOMAIN: service.nomad
      COREDNS_PREFER_CIDR: 10.0.0.0/8
    pid: host
    ipc: host
    uts: host
    privileged: true
    network_mode: host
    restart: always
    healthcheck:
      test:
      - CMD
      - /bin/sh
      - -c
      - wget -O - -q "http://127.0.0.1:8080/health" | grep -q 'OK'
      interval: 5s
      timeout: 1s
      retries: 1
      start_period: 30s

    # Trigger graceful shutdown with SIGINT which CoreDNS is listening
    # and give it 1 minute handle active connections before killing container
    stop_grace_period: 1m
    stop_signal: SIGINT

configs:
  nacp-config.hcl:
    name: "nacp-config.hcl"
    file: ./nacp-config.hcl

volumes:
  nomad:
    name: nomad
    driver: local
