services:
  nomad:
    image: ollijanatuinen/nomad-simplified:${VERSION}
    container_name: nomad${NOMAD_NODE_NUM}
    hostname: nomad${NOMAD_NODE_NUM}
    command: nomad agent -server -config=/etc/nomad.d -config=/etc/nomad.d/role/server.hcl -bind=${NODE_IP} -region=${REGION} -dc=${DATACENTER}
    # command: nomad agent -client -config=/etc/nomad.d -config=/etc/nomad.d/role/client.hcl -region=${REGION} -dc=${DATACENTER} -node-pool=${NODE_POOL}
    environment:
      NOMAD_ADDR: http://${NOMAD_NODE_IP}:4646
      SERVER1: ${SERVER1}
      SERVER2: ${SERVER2}
      SERVER3: ${SERVER3}
    network_mode: host
    uts: host
    pid: host
    ipc: host
    privileged: true
    restart: always
    volumes:
    - nomad:/opt/nomad
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./tls:/opt/tls:ro

volumes:
  nomad:
    name: nomad
    driver: local
