services:
  vault:
    image: hashicorp/vault:${VAULT_VERSION}
    container_name: vault
    entrypoint: sh -c 'vault server -config=/etc/vault.d/vault.hcl'
    environment:
      VAULT_RAFT_NODE_ID: ${HOSTNAME}
      VAULT_API_ADDR: https://${HOSTNAME}:8200
      VAULT_CLUSTER_ADDR: https://${HOSTNAME}:8201
      VAULT_ADDR:  https://0.0.0.0:8200
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      VAULT_AZUREKEYVAULT_VAULT_NAME: ${VAULT_AZUREKEYVAULT_VAULT_NAME}
      VAULT_AZUREKEYVAULT_KEY_NAME: ${VAULT_AZUREKEYVAULT_KEY_NAME}
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ./certs:/opt/certs
      - ./vault/config:/etc/vault.d
      - vault:/opt/vault

  consul:
    image: hashicorp/consul:${CONSUL_VERSION}
    container_name: consul
    entrypoint: sh -c 'consul agent -server -config-dir=/etc/consul.d'
    #entrypoint: sleep 60s
    environment:
      CONSUL_ENCRYPT: ${CONSUL_ENCRYPT}
    privileged: true
    network_mode: host
    restart: always
    volumes:
      - ./certs:/opt/certs
      - ./consul/config:/etc/consul.d
      - consul/data:/opt/consul

volumes:
  vault:
    name: vault
    driver: local
  consul:
    name: consul
    driver: local

