# Simulate three Docker hosts by running docker in docker
x-service-docker: &service-docker
  image: docker:26.1.4
  privileged: true
  volumes:
    - /home/rancher/code/nomad-simplified:/source
  working_dir: /source
  environment:
    AZURE_TENANT_ID: ${AZURE_TENANT_ID}
    VAULT_AZUREKEYVAULT_VAULT_NAME: ${VAULT_AZUREKEYVAULT_VAULT_NAME}
    VAULT_AZUREKEYVAULT_KEY_NAME: ${VAULT_AZUREKEYVAULT_KEY_NAME}
    CONSUL_TEMPLATE_VERSION: ${CONSUL_TEMPLATE_VERSION}
    CONSUL_VERSION: ${CONSUL_VERSION}
    NOMAD_VERSION: ${NOMAD_VERSION}
    VAULT_VERSION: ${VAULT_VERSION}
    CONSUL_ENCRYPT: FzwBN7TZj5hEvV83W6emSP9AUdHDgG

services:
  node1:
    <<: *service-docker
    container_name: node1
    hostname: node1
    networks:
      test:
        ipv4_address: 10.10.10.11

  node2:
    <<: *service-docker
    container_name: node2
    hostname: node2
    networks:
      test:
        ipv4_address: 10.10.10.12

  node3:
    <<: *service-docker
    container_name: node3
    hostname: node3
    networks:
      test:
        ipv4_address: 10.10.10.13

  # Mimics Azure Managed Identity service
  azure-identity:
    container_name: azure-identity
    image: burmilla/os-azureidentity:v1
    network_mode: host
    environment:
      AZIDENTITY_TENANTID: ${AZURE_TENANT_ID}
      AZIDENTITY_CLIENTID: ${AZURE_CLIENT_ID}
      AZIDENTITY_SECRET: ${AZURE_CLIENT_SECRET}

networks:
  test:
    driver: bridge
    name: test
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
