services:
  vault-init:
    image: hashicorp/vault:1.18.1
    container_name: vault-init
    entrypoint: sh -c 'mkdir /opt/vault/data && vault server -config=/etc/vault.d/vault.hcl'
    volumes:
      - ./vault/init-config:/etc/vault.d
      - ./vault:/opt/vault
    privileged: true
    network_mode: host
    environment:
      VAULT_RAFT_NODE_ID: vault1
      # VAULT_API_ADDR: https://vault1:8200
      VAULT_API_ADDR: https://127.0.0.1:8200
      #VAULT_API_ADDR: unix:///run/vault-api.sock
      #VAULT_CLUSTER_ADDR: https://vault1:8201
      # VAULT_CLUSTER_ADDR: https://127.0.0.1:8201
      #VAULT_CLUSTER_ADDR: unix:///run/vault-cluster.sock
  #     - VAULT_ADDR=http://127.0.0.1:8200
  #     - VAULT_API_ADDR=http://127.0.0.1:8200
      VAULT_ADDR: unix:///run/vault.sock
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      VAULT_AZUREKEYVAULT_VAULT_NAME: ${VAULT_AZUREKEYVAULT_VAULT_NAME}
      VAULT_AZUREKEYVAULT_KEY_NAME: ${VAULT_AZUREKEYVAULT_KEY_NAME}
