services:
  vault-init:
    image: hashicorp/vault:1.17.6
    container_name: vault-init
    entrypoint: sh -c 'mkdir /opt/vault/data && vault server -config=/etc/vault.d/vault.hcl'
    volumes:
      - ./secrets:/opt/secrets
      - ./vault/init-config:/etc/vault.d
      - vault:/opt/vault
    privileged: true
    network_mode: host
    environment:
      VAULT_RAFT_NODE_ID: vault1
      VAULT_SKIP_VERIFY: true
      VAULT_ADDR: https://127.0.0.1:8200
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      VAULT_AZUREKEYVAULT_VAULT_NAME: ${VAULT_AZUREKEYVAULT_VAULT_NAME}
      VAULT_AZUREKEYVAULT_KEY_NAME: ${VAULT_AZUREKEYVAULT_KEY_NAME}

volumes:
  vault:
    name: vault
    driver: local
