services:

  # TODO: Add consul-template

  consul:
    image: hashistack:dev-v1
    #user: consul
    container_name: consul
    hostname: ${HOSTNAME}
    command: consul agent -server -config-dir=/etc/consul.d -config-file=/etc/consul.d/role/server.hcl -bind=${HOST_IP}
    # entrypoint: consul agent -config-dir=/etc/consul.d -config-file=/etc/consul.d/role/client.hcl
    #entrypoint: sleep 120s
    environment:
      CONSUL_ENCRYPT: ${CONSUL_ENCRYPT} # Generate with "consul keygen"
      CONSUL_RETRY_JOIN1: ${CONSUL_RETRY_JOIN1}
      CONSUL_RETRY_JOIN2: ${CONSUL_RETRY_JOIN2}
      HOST_IP: ${HOST_IP}
    network_mode: host
    restart: always
    volumes:
      - consul:/opt/consul
      - tls:/opt/tls

volumes:
  consul:
    name: consul
    driver: local
  tls:
    name: tls
    driver: local
